// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRMrJo8GT-yO-N2E19pPte7H0DOoi-yWc',
    appId: '1:132445943973:android:73f04236f9899a7802754c',
    messagingSenderId: '132445943973',
    projectId: 'momentum-planner-fa649',
    storageBucket: 'momentum-planner-fa649.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJrSs2j96JCX1TY82yPuyg1S6edjFzre4',
    appId: '1:132445943973:ios:52a6119feec9877002754c',
    messagingSenderId: '132445943973',
    projectId: 'momentum-planner-fa649',
    storageBucket: 'momentum-planner-fa649.firebasestorage.app',
    iosBundleId: 'com.example.momentumPlanner',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBx0nrYx79g7vohKgP7JUlS3lAyN8TEZGY',
    appId: '1:132445943973:web:030b3876023f30dc02754c',
    messagingSenderId: '132445943973',
    projectId: 'momentum-planner-fa649',
    authDomain: 'momentum-planner-fa649.firebaseapp.com',
    storageBucket: 'momentum-planner-fa649.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJrSs2j96JCX1TY82yPuyg1S6edjFzre4',
    appId: '1:132445943973:ios:52a6119feec9877002754c',
    messagingSenderId: '132445943973',
    projectId: 'momentum-planner-fa649',
    storageBucket: 'momentum-planner-fa649.firebasestorage.app',
    iosBundleId: 'com.example.momentumPlanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBx0nrYx79g7vohKgP7JUlS3lAyN8TEZGY',
    appId: '1:132445943973:web:22d4e2b8824cfe7a02754c',
    messagingSenderId: '132445943973',
    projectId: 'momentum-planner-fa649',
    authDomain: 'momentum-planner-fa649.firebaseapp.com',
    storageBucket: 'momentum-planner-fa649.firebasestorage.app',
  );

}