// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;  // 웹 플랫폼이므로 웹 설정을 반환합니다.
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXbe02V_ooeDDD-BRD8B1LQOncGYJiw5w',
    appId: '1:291736505414:android:34c67505ffbf5f5f858e47',
    messagingSenderId: '291736505414',
    projectId: 'events-e7911',
    storageBucket: 'events-e7911.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwvxIw_XWqMICR4MrfgGi8EuqInscFGGQ',
    appId: '1:291736505414:ios:24a7fefa3e4d7098858e47',
    messagingSenderId: '291736505414',
    projectId: 'events-e7911',
    storageBucket: 'events-e7911.firebasestorage.app',
    iosBundleId: 'com.example.momentumPlanner',
  );

  // 웹용 Firebase 설정 추가
  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyBx0nrYx79g7vohKgP7JUlS3lAyN8TEZGY",
      authDomain: "momentum-planner-fa649.firebaseapp.com",
      projectId: "momentum-planner-fa649",
      storageBucket: "momentum-planner-fa649.firebasestorage.app",
      messagingSenderId: "132445943973",
      appId: "1:132445943973:web:22d4e2b8824cfe7a02754c"

  );
}
